### PR TITLE
Add docstrings for _version.py (pep257 compliance)

### PR DESCRIPTION
**Pull request by glennmatthews**
I've been experimenting with adding `pep257` (docstring) validation to my project and noticed that the generated _version.py fails as it doesn't have docstrings for some of the methods. These are some simple diffs to fix that.

### CODE REVIEW

**Comment by pelson** [comment]
:+1:

**Comment by glennmatthews** [comment]
Ugh - had stale files and didn't realize this wasn't completely working yet. Will fix and update.

**Comment by warner** [comment]
Looks good, thanks! You might want to test the generated `versioneer.py` too, since that is also a file that gets added to project source trees, and projects which do pep257 checks against everything will have problems if it's non-compliant. (we do flake8 checks on both.. does flake8 have a pep257 plugin?)

**Comment by warner** [comment]
Landed (in rebased form to deal with conflicts) in 8080087.

**Comment by glennmatthews** [comment]
Looks like there is a flake8 plugin - https://pypi.python.org/pypi/flake8-docstrings/0.1.2 - but I haven't tried it yet myself. I'll take a look at updating versioneer.py with docstrings and using the flake8-docstrings plugin as well.

Thanks!

**Pull request closed without merging**
