### PR TITLE
fix_typos

### PR DESCRIPTION
**Pull request by delirious-lettuce**
I noticed a typo in your README and then found a few more. This PR should fix them.

### CODE REVIEW

**Comment by warner** [comment]
looks good, landing (in rebased form) momentarily

**Comment by delirious-lettuce** [comment]
Thanks for your time!

**Comment by warner** [comment]
no problem.. sorry it took so long for me to land!

**Comment by delirious-lettuce** [comment]
No worries, it wasn't a very useful PR anyways!

Just wanted to say I'm a fan of magic wormhole too, nice work!

**Pull request closed without merging**
