### PR TITLE
Add required batch file.

### LINKED ISSUE #104: pip install versioneer results in non functioning script on windows
when I pip install versioneer on windows a `versioneer` file is created in Python27/Scripts, but it is not recognized as a python script. i.e. when I run `versioneer install` I get an error about versioneer not being a recognized command. If I change `versioneer` to `versioneer.py` and run `versioneer.py install` it works fine. 

Windows 7
python 2.7.10
pip 7.1.2

### PR DESCRIPTION
**Pull request by xoviat**
This Fixes #104 and #131.

### CODE REVIEW

**Comment by xoviat** [comment]
Well, things are failing but it's not my fault:

    pip requires Python '>=2.6,!=3.0.*,!=3.1.*,!=3.2.*' but the running Python is 3.2.5

    ERROR: InvocationError: '/home/travis/build/warner/python-versioneer/.tox/py3.5/bin/flake8 git_version.py versioneer.py'

**Comment by warner** [comment]
That looks awesome. I'm a bit surprised that `subprocess.call` handles spaces-in-path better than `os.execl`, but I'm not gonna complain if it works :).

Could you rebase this to current trunk and re-push? The PEP8 stuff should be fixed now, and I'd like to have a slightly cleaner merge history when we're done. Thanks!

**Comment by xoviat** [comment]
> Could you rebase this to current trunk and re-push? The PEP8 stuff should be fixed now, and I'd like to have a slightly cleaner merge history when we're done. Thanks!

Done.

**Comment by warner** [comment]
did you push it to the same branch that this PR is using? I didn't see Travis fire.

**Comment by xoviat** [comment]
image

**Comment by warner** [comment]
ah, got it, thanks

**Pull request merged**
